############################################
#  Lemon Grove                             #
#  https://github.com/tajmone/lemon-grove  #
############################################

dist: trusty

language: c
compiler: gcc

git:
  depth: false

cache:
  apt: true
  timeout: 604800

before_script:
  - $CC --version

install:
  - npm install -g eclint

jobs:
    include:
    # ==============================================
    # EditorConfig Code Styles Validation via EClint
    # ==============================================
    # https://editorconfig.org
    # https://www.npmjs.com/package/eclint
    - name: "EditorConfig Validation"
      script:
        - bash ./validate.sh
    # =================================
    # Validate all Contributed Examples
    # =================================
    - name: "Build Examples"
      script:
        - |
          set -e

          for d in $(find $TRAVIS_BUILD_DIR/lemon/examples/* -type d) ; do
              cd $d
              make CC=$CC
              make test
              make clean
              cd $TRAVIS_BUILD_DIR
          done
