--  This file is generated by lemon.
--  DO NOT EDIT.

package Calc_Ada is

   PLUS                           : constant :=   1;
   MINUS                          : constant :=   2;
   DIVIDE                         : constant :=   3;
   TIMES                          : constant :=   4;
   INTEGER                        : constant :=   5;

end Calc_Ada;
